In [2]:
# hstack -- horizontally(column wise)
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [3]:
c = np.array(([1],[2],[3]))
d = np.array(([1],[2],[3]))
np.hstack((c,d))

array([[1, 1],
       [2, 2],
       [3, 3]])

In [4]:
# vstack -- vertical (row wise)
a = np.array((1,2,3))
b = np.array((4,5,6))
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
c = np.array(([1],[2],[3]))
d = np.array(([1],[2],[3]))
np.vstack((c,d))

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3]])

- Pandas
    - one of the data science package
    - used for data manupulation tool,data analysis and data cleaning
    - Its built on numpy package
    - developed by WesMCKinney
- Installation
    - for windows
        - pip install pandas
    - for linux
        - sudo apt-get install python3 pandas
 - Key structures
     - Series
     - data frame
- Series
    - Sequence of data
    - 

In [6]:
import pandas as pd
pd.__version__

'0.23.4'

In [7]:
st = 'Hello'
pd.Series(st)

0    Hello
dtype: object

In [8]:
st1 = input().split()
pd.Series(st1)

python program


0     python
1    program
dtype: object

In [9]:
li = [123,'abc','xyz',2.5]
pd.Series(li)

0    123
1    abc
2    xyz
3    2.5
dtype: object

In [11]:
li1 = [1,2,3,4,'a']
pd.Series(li1)

0    1
1    2
2    3
3    4
4    a
dtype: object

In [15]:
li2 = [1,2,3,4,'a']
pd.Series(li2,index=['A','B','C','D','E'])

A    1
B    2
C    3
D    4
E    a
dtype: object

In [16]:
li3 = [1,2,3,4,'a']
pd.Series(li3,index=['A','B','C','D'])

ValueError: Length of passed values is 5, index implies 4

In [12]:
t = ('c','k',7)
pd.Series(t)

0    c
1    k
2    7
dtype: object

In [13]:
d = {'Name':'Python','branch':'ALL','Org':'APSSDC'}
pd.Series(d)

Name      Python
branch       ALL
Org       APSSDC
dtype: object

In [14]:
d1 = {'Name':'Python','branch':'ALL','Org':'APSSDC'}
pd.Series(d1,index=['Name','Branch','org'])

Name      Python
Branch       NaN
org          NaN
dtype: object

In [ ]:
li = [123,"abc",41.65]
pd.Series(li,index=['A','B','C'])

In [17]:
d={'name':'jaggi','age':24,'sal':3.5}
pd.Series(d,index=['name','AGE','SALARY'])

name      jaggi
AGE         NaN
SALARY      NaN
dtype: object

In [19]:
ar = np.arange(4,10)
pd.Series(ar)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int32

In [21]:
r = np.random.randint(2,20,8)
r1 = pd.Series(r)
r1

0    18
1     2
2     8
3    16
4    16
5     3
6     8
7    13
dtype: int32

In [ ]:
- syntax[start:end:step]

In [22]:
r1[0:4]

0    18
1     2
2     8
3    16
dtype: int32

In [24]:
r1[5:]

5     3
6     8
7    13
dtype: int32

In [25]:
r1[:6]

0    18
1     2
2     8
3    16
4    16
5     3
dtype: int32

In [26]:
r1[0:6:2]

0    18
2     8
4    16
dtype: int32

In [28]:
r=np.random.randint(2,20,5)
r1=pd.Series(r)
r1

0    10
1    15
2    15
3     5
4     6
dtype: int32

index    values
1          1
2          4
3          9
4          16

In [30]:
k=np.arange(1,11)
a=np.square(k)
pd.Series(a)

0      1
1      4
2      9
3     16
4     25
5     36
6     49
7     64
8     81
9    100
dtype: int32

In [31]:
ar1 = np.arange(int(input()))
ar2 = np.square(ar1)
pd.Series(ar2)

5


0     0
1     1
2     4
3     9
4    16
dtype: int32

In [32]:
num = int(input())
l = {i:i**2 for i in range(1,num)}
o = pd.Series(l)
o

10


1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int64

In [33]:
pd.Series(np.array(range(1,10))**2,index=range(1,10))

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

- DataFrame
    - data in rows and columns
    - create and retrive

In [38]:
name = input().split()
pd.DataFrame(name)

python program


0
0   python
1  program

In [39]:
name1 = input().split()
pd.DataFrame(name1,index=['A','B'],columns=['Data'])

python program


Data
A   python
B  program

In [47]:
data = [['Python','Program'],['Django','Webdevelopment'],['Flask','Webdevelopment']]
pd.DataFrame(data)
pd.DataFrame(data,index=['One','Two','Three'])
pd.DataFrame(data,columns=['Language','Usuage'])
pd.DataFrame(data,index=['One','Two','Three'],columns=['Language','Application'])

Language     Application
One     Python         Program
Two     Django  Webdevelopment
Three    Flask  Webdevelopment

In [49]:
lone = [[1,2,3,8,9],[4,5,6]]
pd.DataFrame(lone)

0  1  2    3    4
0  1  2  3  8.0  9.0
1  4  5  6  NaN  NaN

In [51]:
d = {'Name':'Python','Branch':'ALL','Org':'APSSDC'}
pd.DataFrame(d,index=[1])

Name Branch     Org
1  Python    ALL  APSSDC

In [55]:
d1 = {'key1':'value1','key2':'value2'}
d2 = {'key3':'value3','key1':'value4'}
pd.DataFrame(d1,d2)

key1    key2
key3  value1  value2
key1  value1  value2

In [57]:
d3 = {'key1':'value1','key2':'value2'}
d4 = {'key3':'value3','key1':'value4'}
pd.DataFrame([d3,d4],index=['A','B'])

key1    key2    key3
A  value1  value2     NaN
B  value4     NaN  value3

In [58]:
d3 = {'key1':'value1','key2':'value2'}
d4 = {'key3':'value3','key1':'value4'}
pd.DataFrame([d3,d4],index=['A','B'],columns=['key1','key2','Key3'])

key1    key2  Key3
A  value1  value2   NaN
B  value4     NaN   NaN

In [78]:
T1 = {'Name':'Pavani','Org':'APSSDC','Team':'Gaming'}
T2 = {'Name':'Ambika','Org':'APSSDC','Team':'Python','Year':'2017'}
T3 = {'Name':'Vanitha','Org':'APSSDC','Team':'C & DS','Exp':'2'}
T4 = {'Name':'Archana','Org':'APSSDC','Team':'Cyber'}
s = pd.DataFrame([T1,T2,T3,T4])
a = pd.DataFrame([T1,T2,T3,T4],index=['One','Two','Three','Four'])
v = pd.DataFrame([T1,T2,T3,T4],index=['One','Two','Three','Four'],columns=['Name','Org','Team','Year','Exp'])
v

Name     Org    Team  Year  Exp
One     Pavani  APSSDC  Gaming   NaN  NaN
Two     Ambika  APSSDC  Python  2017  NaN
Three  Vanitha  APSSDC  C & DS   NaN    2
Four   Archana  APSSDC   Cyber   NaN  NaN

- Retive data Frames
    - loc
        - index data
    - iloc
        - index position

In [79]:
v

Name     Org    Team  Year  Exp
One     Pavani  APSSDC  Gaming   NaN  NaN
Two     Ambika  APSSDC  Python  2017  NaN
Three  Vanitha  APSSDC  C & DS   NaN    2
Four   Archana  APSSDC   Cyber   NaN  NaN

In [80]:
v.loc['One']

Name    Pavani
Org     APSSDC
Team    Gaming
Year       NaN
Exp        NaN
Name: One, dtype: object

In [81]:
v.iloc[0]

Name    Pavani
Org     APSSDC
Team    Gaming
Year       NaN
Exp        NaN
Name: One, dtype: object

In [82]:
v.loc['Four']

Name    Archana
Org      APSSDC
Team      Cyber
Year        NaN
Exp         NaN
Name: Four, dtype: object

In [83]:
v.iloc[3]

Name    Archana
Org      APSSDC
Team      Cyber
Year        NaN
Exp         NaN
Name: Four, dtype: object

In [84]:
a

Exp     Name     Org    Team  Year
One    NaN   Pavani  APSSDC  Gaming   NaN
Two    NaN   Ambika  APSSDC  Python  2017
Three    2  Vanitha  APSSDC  C & DS   NaN
Four   NaN  Archana  APSSDC   Cyber   NaN

In [85]:
# Add column
a['Language'] = ['Python','C','Java','C++']
a

Exp     Name     Org    Team  Year Language
One    NaN   Pavani  APSSDC  Gaming   NaN   Python
Two    NaN   Ambika  APSSDC  Python  2017        C
Three    2  Vanitha  APSSDC  C & DS   NaN     Java
Four   NaN  Archana  APSSDC   Cyber   NaN      C++

In [86]:
s

Exp     Name     Org    Team  Year
0  NaN   Pavani  APSSDC  Gaming   NaN
1  NaN   Ambika  APSSDC  Python  2017
2    2  Vanitha  APSSDC  C & DS   NaN
3  NaN  Archana  APSSDC   Cyber   NaN

In [87]:
s.T

0       1        2        3
Exp      NaN     NaN        2      NaN
Name  Pavani  Ambika  Vanitha  Archana
Org   APSSDC  APSSDC   APSSDC   APSSDC
Team  Gaming  Python   C & DS    Cyber
Year     NaN    2017      NaN      NaN

In [88]:
s

Exp     Name     Org    Team  Year
0  NaN   Pavani  APSSDC  Gaming   NaN
1  NaN   Ambika  APSSDC  Python  2017
2    2  Vanitha  APSSDC  C & DS   NaN
3  NaN  Archana  APSSDC   Cyber   NaN

In [89]:
s.drop(1)

Exp     Name     Org    Team Year
0  NaN   Pavani  APSSDC  Gaming  NaN
2    2  Vanitha  APSSDC  C & DS  NaN
3  NaN  Archana  APSSDC   Cyber  NaN

In [90]:
s

Exp     Name     Org    Team  Year
0  NaN   Pavani  APSSDC  Gaming   NaN
1  NaN   Ambika  APSSDC  Python  2017
2    2  Vanitha  APSSDC  C & DS   NaN
3  NaN  Archana  APSSDC   Cyber   NaN

In [91]:
df1 = pd.DataFrame({"num":[1,2,3,4],
                   "age":[25,30,35,40]},
                  index=[2000,2001,2002,2003])
df1

num  age
2000    1   25
2001    2   30
2002    3   35
2003    4   40

In [92]:
df2 = pd.DataFrame({"num1":[11,12,3,4],
                   "age1":[25,35,55,40]},
                  index=[2001,2002,2003,2005])
df2

num1  age1
2001    11    25
2002    12    35
2003     3    55
2005     4    40

In [93]:
# combine data on key column or an index
df1.join(df2)

num  age  num1  age1
2000    1   25   NaN   NaN
2001    2   30  11.0  25.0
2002    3   35  12.0  35.0
2003    4   40   3.0  55.0

In [94]:
df2.join(df1)

num1  age1  num   age
2001    11    25  2.0  30.0
2002    12    35  3.0  35.0
2003     3    55  4.0  40.0
2005     4    40  NaN   NaN

In [95]:
df3 = pd.DataFrame({"weight":[80,90,60,70],
                   "num":[2,1,2,3],
                   "age":[50,45,45,67]},
                  index=[2001,2002,2003,2004])
df3

weight  num  age
2001      80    2   50
2002      90    1   45
2003      60    2   45
2004      70    3   67

In [96]:
df4 = pd.DataFrame({"weight":[80,69,60,70],
                   "num":[2,1,2,3],
                   "age":[50,45,45,67]},
                  index=[2001,2005,2006,2008])
df4

weight  num  age
2001      80    2   50
2005      69    1   45
2006      60    2   45
2008      70    3   67

In [97]:
# used to combine dataframes on basis of common column or indices
df3.merge(df4)

weight  num  age
0      80    2   50
1      60    2   45
2      70    3   67

In [98]:
df3.merge(df4,on='weight')

weight  num_x  age_x  num_y  age_y
0      80      2     50      2     50
1      60      2     45      2     45
2      70      3     67      3     67

In [99]:
# used to append dataframes one below the other
con = pd.concat([df1,df2])
con

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


age  age1  num  num1
2000  25.0   NaN  1.0   NaN
2001  30.0   NaN  2.0   NaN
2002  35.0   NaN  3.0   NaN
2003  40.0   NaN  4.0   NaN
2001   NaN  25.0  NaN  11.0
2002   NaN  35.0  NaN  12.0
2003   NaN  55.0  NaN   3.0
2005   NaN  40.0  NaN   4.0